---
blendingMode: 1
jpgQuality: 0.5
resolution: 0.6666667
producer: null
creator: ""
producerOverridden: false
zoomSpeed: 1.01
invertZoom: false
selectionColor: "FF00FF"
maxOverlays: 5
language: "en"
usedOverlays:
  png/paid_stamp.png: 5
  png/coffee-stains_1.png: 1
  png/coffee-stains_2.png: 5
  png/pushkin_2.png: 2
  png/pushkin_1.png: 8
